### ISSUE TITLE
Bug: Rights field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#112]
After selecting and saving 'All rights reserved', the phrase shows up twice when viewing the record: http://staging.hydra.chemheritage.org/files/9880vt42g

**Comment by hackmastera** [comment]
The problem is due to the fact that most rights statements are configured with a label and a url. all rights reserved just uses the label in both places. need to look more deeply into exactly how this breaks, but it's definitely a universal sufia problem (not local).

**Comment by hackmastera** [comment]
The field is designed to support 2 links. The first is a link to a search for other records with that same value in the rights field (i.e. in this case, every item that's 'all rights reserved'). The second is a link to the extern url, and is supposed to show up as a 'new window' icon. In this case the second link isn't created correctly and instead of just not showing up it repeats the label text.

**Comment by hackmastera** [comment]
Discussed with Cat on Friday. We're going to backburner this for now for two reasons:
1. The problem arises from assumptions made upstream; a good fix isn't clear to me right now.
2. It will potentially be obviated when we have a full list of rights statements
3. It's a front-end issue that will become more important when we're preparing for public visibility.

Meanwhile I'm filing a sufia issue.

**Comment by hackmastera** [comment]
https://github.com/projecthydra/sufia/issues/1356

**Comment by hackmastera** [comment]
I fixed this upstream but we also removed the 'all rights reserved' option so this issue is resolved.
