### ISSUE TITLE
Ensure we are displaying a success message after new version uploads

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#223]
Under the "Versions" tab in the edit page, when a user chooses to "Upload New Version" of a photo, there is a delay of several minutes before displaying the updated version in the thumbnail. This has led to users re-uploading the file multiple times because they think the update didn't work the first time. Multiple copies of the file are unnecessarily being saved in the versioning. 

Why is there a delay? Is there a way to make the thumbnail display the updated version immediately upon saving?

**Comment by hackmastera** [comment]
Thumbnail generation is backgrounded in order to allow users to continue their work while the derivatives are being generated. Several minutes seems unlikely and I have found that users tend to overestimate the length of time they waited when they report these types of things.

I believe this is normal / expected behavior. When an item is created for the first time, a message appears after it is saved stating that thumbnails will be created in the background and they may need to refresh. Maybe we need to be sure this message also appears when versions are added. But it's also likely that even if we have these there will be users who don't notice them and/or don't read them.

**Comment by hackmastera** [comment]
@catlu timed this at 11 min!!

**Comment by hackmastera** [comment]
@sanfordd timed it at 30 seconds, and it comes through fast in an incognito window. latest theory is that it's a cache issue.

**Comment by MDiMeo** [comment]
Cat's new workflow with Tianna means this shouldn't happen again.
