### ISSUE TITLE
resource type data needs to be converted to URIs

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#234]
Strings pulled over during migration are breaking the renderer.

**Comment by hackmastera** [comment]
related: https://github.com/chemheritage/chf-sufia/issues/218

I think the best thing to do for now is to use only strings for these values. Once the upstream fix is in place we can re-introduce the URIs.

**Comment by jrochkind** [comment]
@hackmastera I want to work on this, but don't completely understand what needs to be done. Can you give an example?

**Comment by jrochkind** [comment]
`./config/authorities/resource_types.yml`

`id` should be a URI, not a label. If fixed, there is data cleanup to do to match. 

Right now, we have a bunch of RDF 'object' values that are strings like "Image" instead of URIs like `http://purl.org/dc/dcmitype/StillImage`, which doesn't technically violate the range of the predicate we're using `http://purl.org/dc/elements/1.1/type`, although is not a great practice. 

But in the end, this effects nothing right now and we don't need to spend time on it at present.
