### ISSUE TITLE
When adding parent work, work shows up twice

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#264]
![capture](https://cloud.githubusercontent.com/assets/11876037/21367401/f48ec046-c6cb-11e6-83b4-670ca49d164b.PNG)

**Comment by hackmastera** [comment]
I'm nearly sure this is the same issue as #243. As in that issue, editing the work again and saving it with no changes resolves the problem.

Problem seems to extend therefore to any object relationship.

I've tried this in sufia master and in sufia 7.2 and do not see the bug in either. So it must be due to some local code.

**Comment by hackmastera** [comment]
(unless it's somehow related to rails version, which is the only other difference of any significance between the tests I've done.)

**Comment by hackmastera** [comment]
plan to use git-bisect to figure out when this error was introduced.

**Comment by hackmastera** [comment]
looks like the javascript is being initialized twice, which binds the add button twice, etc.
