### ISSUE TITLE
periodic fixity checks

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#276]
maybe helpful: https://github.com/ClevelandArtGIT/cma-archives/blob/master/app/services/cma/fixity_service.rb

https://github.com/ClevelandArtGIT/cma-archives/blob/master/app/models/fixity.rb

**Comment by jrochkind** [comment]
~~~
Jonathan Rochkind [12:30 PM] 
okay, so fedora 4 is already storing SHA1s for all files.  So the next step would be verifying them…. is there anything in currently existing stack to do that? (and correct me if I’m getting anything wrong in my assumptions please, trying to get em right!) (edited)

escowles 
[12:31 PM] 
based on the spec, you'd need to retrieve the SHA1 property, and also retrieve the checksum for the content, and compare them

[12:31] 
basically, doing a HEAD on the binary to get the checksum, and then a GET on the binary description to get the stored checksum

Jonathan Rochkind [12:32 PM] 
1. Where is this spec you speak of? 2. and there’s nothing in fedora or hydra stack to currently do that for? GET and compare to stored checksum?

[12:32] 
3. Does anyone know how many if any current sufia/hydra users are doing this?

escowles 
[12:32 PM] 
1. the spec is in github: https://github.com/fcrepo/fcrepo-specification

Jonathan Rochkind [12:33 PM] 
Okay, somewhere in that spec repo I’ll find some parts that talk about “you’d need to retrieve the SHA1 property, and also retrieve the checksum for the content, and compare them”?

new messages
hackmaster.a [12:33 PM] 
@jrochkind the thing I’m thinking of that I thought was fixty related is this audit service https://github.com/projecthydra/sufia/blob/master/app/services/sufia/repository_audit_service.rb

escowles 
[12:33 PM] 
2. i believe that ActiveFedora can do the current fixity check (there's a special fcr:fixity endpoint), and i think there's some functionality in sufia to do that, but i'm not sure
~~~

https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/file_set_audit_service.rb

**Comment by jrochkind** [comment]
I think most of this discussion is about features fc_repo does not actually have at present, but:

https://github.com/fcrepo/fcrepo-specification/issues/90

My impression is that hardly anyone using hydra stack is actually doing fixity checks at present --
 I wasn't able to get anyone in Slack to say they were or knew anyone that was. 

Consequently the curation_concerns file_set_audit_service thing may or may not actually work well, it's probably gotten very little attention or use. We will find out at some point.

**Comment by jrochkind** [comment]
narogers wrote the one at https://github.com/ClevelandArtGIT/cma-archives/blob/master/app/services/cma/fixity_service.rb

He says he never really used in in production. He had considered "write up an alert service that would run in the background, cherry pick a couple thousand files, and then do the checks" -- which implies it would be infeasible to check _everything_, he was just going to take a sample! Although a couple thousand is all of ours, so. 

narogers says he also believes there may be zero institutions with hydra or fedora actually doing fixity checks in production.

**Comment by hackmastera** [comment]
Initial use case: Once a file is in fedora, if it changes at all, we find out about it.

**Comment by jrochkind** [comment]
Some more source material:

* https://github.com/psu-stewardship/scholarsphere/blob/develop/script/audit_repository


* https://github.com/projecthydra/curation_concerns/blob/master/app/jobs/audit_job.rb
* https://github.com/projecthydra/sufia/blob/818cb4ca53d81fdb37835a0cd7c753d66eacd679/app/services/sufia/repository_audit_service.rb

One of those is sufia 6, one sufia 7, not sure which is which.

**Comment by hackmastera** [comment]
@jrochkind PSU/scholarsphere is on sufia 6 so that will be the sufia 6 stuff.

most of curation_concerns master is sufia 7 but it's safer to look at the 1-7-stable branch.

the sufia one is probably sufia 7 stuff.

**Comment by jrochkind** [comment]
It took me a while to figure out that existing sufia had existing tools for fixity auditing (thanks Hydra slack), and to figure out how they worked. While normally I live with using hydra components without fully understanding them, fixity checking seems like something we want to fully understand what it's doing for confidence. 

Hydra component write-ups seem to be very sensitive. This was investigated under Sufia 7.3.0, CurationConcerns 1.7.7, ActiveFedora 11.1.6. I _believe_ it has not changed substantially in hyrax as of this date, except for class name changes (including generally using 'fixity' instead of 'audit' in class names), but am not totally sure. 

There is an existing service to fixity audit a single FileSet, in [CurationConcerns at FileSetAuditService](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/app/services/curation_concerns/file_set_audit_service.rb).

    CurationConcerns::FileSetAuditService.new(fs).audit

So you might run that on every fileset to do a bulk audit, like `FileSet.find_each { |fs| CurationConcerns::FileSetAuditService.new(f).audit }` — which is just what ([in Sufia](https://github.com/projecthydra/sufia/blob/8bb451451a492e443687f8c5aff4882cac56a131/app/services/sufia/repository_audit_service.rb) rather than CC) `Sufia::RepositoryAuditService` does, nothing more nothing less. 

`CurationConcerns::FileSetAuditService` actually uses several other objects to do the actual work, but the final outcome will be:

* an ActiveRecord ChecksumAuditLog row created -- I believe one for every _file_ checked, in cases where a fileset has multiple files. It seems to have a `pass` (integer column) of `1` if the object had a good checksum, or a `0` if not. 
    * It cleans up after itself in that table, not leaving infinitely growing historical ChecksumAuditLog rows there; generally I think only the most recent two are kept, although may be more if there are failures. [AuditJob calls](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/app/jobs/audit_job.rb#L34) [ChecksumAuditJob.prune_history](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/app/models/checksum_audit_log.rb#L10)
    * While the ChecksumAuditLog record has columns for `expected_result` and `actual_result`, nothing in sufia/CC stack fills these out, all you get is the `pass` value, a `file_set_id`, a `file_id`, and `version` string. 
       * I at present do not understand how the `version` string is used -- does the `file_id` not fully identify an asset, multi-versioned assets share the same `file_id` maybe?  The `version` string looks like `http://127.0.0.1:8080/rest/dev/37/72/0c/72/37720c723/files/214f68af-e5ed-41bd-9898-b8923fd6d018/fcr:versions/version1`. Not completely sure how to go from this info to the actual asset that is not matching it's checksum. 
* On cases of _failure_, it sends an internal app message to the person listed as the _depositor_ of the fileset -- assuming the fixed email address of the depositor still matches the email address of Sufia account. This is set up by [Sufia registering a CurationConcerns callback](https://github.com/projecthydra/sufia/blob/8bb451451a492e443687f8c5aff4882cac56a131/config/initializers/curation_concern_events.rb#L26-L28) to run the [Sufia::AuditFailureService](https://github.com/projecthydra/sufia/blob/8bb451451a492e443687f8c5aff4882cac56a131/app/services/sufia/audit_failure_service.rb); that callback is triggered by the [CurationConcerns::AuditJob](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/app/jobs/audit_job.rb#L14-L18) (AuditJob gets run by the FileSetAuditService). 
   * The internal message does includes the FileSet title and `file_set.original_file.uri.to_s`. If the file set had multiple versions, which one (or how to get to it in UI) that failed the checksum is not included. 
   * This probably isn't the failure callback we'd want (not clear who would want this, honestly, the original depositor does not seem the right person to get a notification for a fixity failure, which is an infrastructure problem), but the architecture makes it easy to register your own `after_audit_failure`. Perhaps to send an email, or register an error with an error service like Bugsnag or Honeybadger. 
   * The callback is using [CurationConcerns::Callback::Registry](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/lib/curation_concerns/callbacks/registry.rb) which only supports one callback per event, so `set`ing another one will replace the one by default set by Sufia. Which is fine. 

**I did intentionally corrupt a file** on my dev copy, and then verify it was caught and these things happened. 

While all the ChecksumAuditLog objects are created, there is no built-in UI for viewing them at all. They're just there as a sort of record that can be manually accessed by a developer or whatever.

## So what's going on

Some notes on implementation, what classes are involved and what they are doing, including how fixity is actually being checked. 

The CurationConcerns::FileSetAuditService actually [calls out](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/app/services/curation_concerns/file_set_audit_service.rb#L91) to [CurationConcerns::AuditJob](https://github.com/projecthydra/curation_concerns/blob/1d5246ebb8bccae0a385280eda10a7dbdc1d517d/app/jobs/audit_job.rb) to do the bulk of it's work. 
   * It insists on calling AuditJob as `perform_later`, there is no way to configure it to run synchronously. 
      * When I ran an audit of every file on staging (with a hand-edit to do them synchronously so I could time it more easily and clearly), it took about 3.8 hours to check 8077 FileSets on staging. 
      * This means a bulk audit, using Resque bg jobs to do it -- could clog up the resque job queue for up to 3.8 hours, making other jobs (like derivatives creation) take a long time to complete, perhaps at the end of the queue 3.8 hours later. Perhaps less if we have more than 1 worker in our resque job pool, but clogging up the job queue for a bulk fixity audit seems problematic. 
      * It's unclear to me the logic of what things are separated between FileSetAuditService and AuditJob, I would architect this somewhat differently with a single service object that can easily be run synchronously or as a bg job. 

The CurationConcerns::AuditJob actually calls out to [ActiveFedora::FixityService](https://github.com/jrochkind/active_fedora/blob/fae7df019337506b53fc721b22414fdc45830f9b/lib/active_fedora/fixity_service.rb) to actually do the fixity check. 
  * How is the fixity check done?
    * ActiveFedora::FixityService simply asks Hydra for a fixity check on a URL (for an individual File, I think). The asset is _not_ downloaded or examined by Hydra stack code, a simple HTTP request "do a fixity check on this file and tell me the result" is sent to Hydra. 
    * This means we are trusting that A) even if the asset has been corrupted, Fedora's stored checksum for the asset is still okay, and B) that the Fedora fixity service actually works.  I guess these are safe assumptions for a reliable fixity service? 
    * It looks at the RDF body returned by the hydra fixity service to interpret if the fixity check was good or not
  * While I _think_ the Hydra fixity service RDF body response includes some additional information (original and current checksum?), this information is not captured and sent up to the stack to be reported or logged. 

## Misc outstanding questions and issues

* I don't really understand why ChecksumAuditLog records success/failure as an _integer_, with 0 and 1... and maybe other numbers? Not sure what this is trying to accomplish, I'd have expected a boolean. The code in FileSetAuditService confuses me a bit, with the way it's saving stuff in a 'log' variable, and doing... something with it.

* The Sufia UI for a FileSet displays a line `Audit Status: Audits have not yet been run on this file`.  This line is not ever updated, even when you've run audits, at least with `CurationConcerns::FileSetAuditService.new(fs).audit`. Not sure what's supposed to be updating it how, or what's broken. Known reported issue https://github.com/projecthydra/sufia/issues/2886 https://github.com/projecthydra-labs/hyrax/issues/188

* Someone told me Sufia intends to run an audit every time a file is viewed (or downloaded?).  I am not sure if this is actually happening or not, I didn't find any evidence of it, or track down code that looks like it's doing it. I'm not sure why this is a desired function anyway -- it seems to me you need to be running periodic bulk/mass audits anyway (you don't want to avoid checking files that haven't been viewed), and if you doing so, additional checking on-the-fly checking when viewed/downloaded seems superfluous. 

* Once you've found a fixity failure (a rare occurence) -- what do you _do_?  Doing nothing but now knowing about a corrupted file does not seem useful, you're doing fixity checks because you're going to do something about it, right?
 Presumably you have backups, and look for one with a matching checksum. If you've found one, how do you restore it in fedora? Do you overwrite the existing file, or add a new 'version', with the former one destined to fail fixity checks forever? How does Fedora intend you to do this (if any), and exactly what info do we need logged to do it succesfully, and do we have this info logged in `ChecksumAuditLog`? (I _think_ so, with the file_id, is probably enough?)

## Ways forward if we want fixity checking

This logic is kind of messy. We could try to use it as best we can; or we could rewrite it/write our own, in whole or in part; if writing our own (in whole or part), we could try to submit changes upstream. The challenge with submitting changes upstream is ideally, especially if spending that time, I kind of want to change how things work drastically, but I'm not sure what current behavior people are relying on, or if there are un-documented reasons unknown to me behind some of the choices made. 

One question is verifying that we're okay with trusting Hydra's fixity service for the fixity check, that this is high enough confidence of fixity. I am guessing it probably is. 

### Minimal choice

We use the existing code, periodically running an audit of every FileSet, **but** we set our own `after_audit_failure` hook to send us (infrastructure admins) an email on fixity failure (instead of sending an internal app message to the depositor). (And/Or log an error with bugsnag or honeybadger or something). 

This would mean it's potentially clogging up the resque job queue though. 

### Slightly more than minimal choice

Above, but we copy-and-paste create a local copy of `CurationConcerns::FileSetAuditService`, that we modify _only_ enough to be able to run the auditjobs synchronously (at least as an option), to avoid clogging up the bg job queue. (Is this possible/easy? Is it enough to run `AuditJob.perform_now`? Not sure). 

And/or submit that change upstream, to give FileSetAuditService a synchronous option. Upstream to hydra I guess. 

### Maximal choice

We rewrite this all, or significantly refactor and add to it, to get:

* Simpler documented code with fewer classes
* Synchronous or optionally synchronous auditing, instead of insisting on using job queue. 
* Log more info than just 'failed', save what hydra fixity service is telling you, possibly including original and current checksum, etc. 
* A UI for viewing the ChecksumAuditLog, or at least any failed ones -- perhaps with a way to mark failed ones as 'resolved'. (although we don't want to rewrite what a bugtracking service like bugsnag or honeybadger does, instead of just using one). 
* Fix the lack of updating the 'Audit status' in FileSet show UI. Possibly by having it consult the AR ChecksumAuditLog instead of requiring an attribute to be synchronized in the fedora object (which is currently apparently buggily not happening).  (unless we want the fixity check status in the fedora object for federation).  An updated 'audit status' might show you more of that info hydra reports, not just 'failed' or 'success'. 

If we do any or all of this, we could try to submit some or all of it back upstream, or keep it local. If submitting back upstream, to be responsible we'd have to figure out what changes can be made without backwards incompat problems, or what existing code that looks 'weird' to me may be neccesary for someone elses case -- can be challenging and/or time-consuming to figure out in hydraland. 

### Don't forget restore

Regardless of what we do, we either need to figure out (and practice/demonstrate) restoring a known-good backup, or decide fixity failure is unlikely to happen so we won't worry about it, and figure it out when it happens. (That's very not good backup practice though, it's best to practice restores to make sure they are in fact _possible_ before you need them.) 

If we figure out how to restore a known-good backup, we could leave it with manual instructions, or write scripts to automate it. If writing scripts to automate it especially, we may want to periodically test the process, perhaps by intentionally corrupting a file on staging, perhaps in an automated cron-like schedule.

**Comment by hackmastera** [comment]
> Perhaps less if we have more than 1 worker in our resque job pool, but clogging up the job queue for a bulk fixity audit seems problematic
We could maybe look at defining more than one queue, with dedicated workers to each.

> This means we are trusting that A) even if the asset has been corrupted, Fedora's stored checksum for the asset is still okay, and B) that the Fedora fixity service actually works. I guess these are safe assumptions for a reliable fixity service?
These are assumptions I know some people don't want to make, leading them to do all their fixity externally.

> ActiveFedora::FixityService simply asks Hydra for a fixity check on a URL (for an individual File, I think)
I suspect it's only running on the most current version.

> I don't really understand why ChecksumAuditLog records success/failure as an integer, with 0 and 1... and maybe other numbers?
I've seen people do this before where they use 0 and 1 instead of bool. I think maybe bool used to take more space or something? Not sure, actually, but I suspect it's an old habit that has fallen our of fashion.

**Comment by jrochkind** [comment]
>  suspect it's only running on the most current version.

*Appears* to be running on every version. https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/file_set_audit_service.rb#L62-L65

> I've seen people do this before where they use 0 and 1 instead of bool. I think maybe bool used to take more space or something? Not sure, actually, but I suspect it's an old habit that has fallen our of fashion.

In some rare cases, it also sets it to 999. Maybe if the fixity check got interrupted or something. I dunno. I only understood so much. :)

**Comment by jrochkind** [comment]
Main decision that needs to be made before proceeding: 

Do we trust Fedora's fixity service (like the code built into hydra does), or do we want to duplicate it ourself, writing code that actually pulls down the binary and calculates the md5 in our own code. 

Subsidiary question if we decide "we do not trust it, we need to do it ourself" -- do we trust fedora's record of the original checksum, or do we need to store checksums somewhere else too, to compare to fedora's stored original checksum?  (If we are trusting fedora's fixity service, then this is not a question, we are trusting fedora's checksum too). 

I have no strong opinions -- it's certainly a lot easier to just trust fedora's fixity service. And if we don't, then it definitely raises into question (again) why we're even using fedora. But I don't really know if it is trustworthy. 

Not really sure how/who to make this decision. @MDiMeo @hackmastera  @sanfordd ?

**Comment by MDiMeo** [comment]
I'm not sure if anything has changed since then, but there was some conversation on the Fedora List Serve and tech calls to discuss Fedora's fixity in December 2016. Some notes are here https://groups.google.com/forum/#!searchin/fedora-community/fixity%7Csort:relevance/fedora-community/tq-vqRaFL3c/JX7EWnnEDQAJ and here https://groups.google.com/forum/#!searchin/fedora-community/fixity%7Csort:relevance/fedora-community/Sks8N5BZrJ4/uMPJ96eKDAAJ

If Fedora is still committed to offering fixity checks as a core service, then I'm okay with trusting that. 

I'm not sure where in the codebase this goes, but if we may have to write something custom that has the potential to be taken on upstream for other Hydra users, would it make more sense to do it in Hyrax?

**Comment by jrochkind** [comment]
See also #495

**Comment by jrochkind** [comment]
How often do we want to run fixity checks on a given file?

The default sufia/hyrax seems to assume once every 7 days is sufficient. But one shouldn't assume the default sufia/hyrax was based on anything in particular. 

@MDiMeo ?

**Comment by MDiMeo** [comment]
7 days works for me if it can do it this quickly. I've heard people say they do it only once or month or twice a year, so I think once a week is great. And most importantly, this should fit safely within the back-up architecture that @sanfordd created.

**Comment by jrochkind** [comment]
@MDiMeo To make sure we're clear:  The fixity job is set up here to _run_ every night.  When it runs, it does go through every file -- and if the file has a fixity check on file in the past 7 days, it moves on and doesn't do another one. 

I am not sure how the range of durations it will take for the nightly fixity job to run, it will depend on how many files need an actual check (haven't gotten one in 7 days), so for instance the first time it runs it will have to check all of them. I don't really know the upper and lower ranges of how long it will take though.

**Comment by MDiMeo** [comment]
Thanks for the clarification. Sounds good. I'll be interested to see how long it takes to run.

**Comment by sanfordd** [comment]
Looks like, as of 6/1/17 a full run took about 5.33 hours (give or take a few minutes).
Stress on the CPU was minimal and the disk I/O was high one one of the two disks but the RAID array should give us a lot of spare read capacity if someone comes by to get a download assuming Sufia is not as sticky as the fixity check on using only one disk.

**Comment by jrochkind** [comment]
The front-end Sufia Rails app itself certainly should not be "sticky" to a CPU in a multi-core setup. 

Sufia is doing nothing but making individual HTTP requests to fedora for the fixity check. So it really depends on the CPU "stickiness" of fedora -- which apparently is not good, for some reason we don't understand. I dunno.
