### ISSUE TITLE
Insert tooltips copy

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#34]

**Comment by hackmastera** [comment]
move to backend UI

**Comment by catlu** [comment]
@hackmastera, the Tool Tips (https://chemheritage.atlassian.net/wiki/display/HDC/Hydra+Tool+Tips) are basically ready to go, except for the rows in red, which are fields we haven't quite figured out in general yet. I erred on the side of longer explanations (because I think it's likely people will use the Tool Tips instead of the metadata guide), but can definitely shorten any Tip that's too long.
