### ISSUE TITLE
Social media icons broken

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#341]
tumblr, google

We will test closer to soft launch when the firewall is gone.

**Comment by jrochkind** [comment]
Probably not working because our app is firewalled, indeed. Facebook def needs to be able to fetch your URL to work properly. Not sure if there's a good way to ensure this is working before soft launch, when soft launch is when this becomes visible to facebook etc!

**Comment by MDiMeo** [comment]
Sounds like the problem with Google+ is the same as that with Facebook: the firewall. 

The bigger issue is Tumblr. I know @hackmastera said above that it takes her to log in page, but it takes me to a 404 page. I had Ashley try it because she regularly posts to Tumblr for Othmeralia and she also got "page not found".

Also, Zach in Communications had previously asked me if we could add a Pinterest icon. If that's something we want, I can either keep it here or make a separate ticket for that and file it in the backlog.

**Comment by jrochkind** [comment]
@MDiMeo I'd choose making a separate ticket. 

Not really sure what to do with _any_ of these without our app being public. Perhaps we can make it temporarily public with a robots.txt. Or figure out what IP's to whitelist for all the social networks, but that could be hard. 

Is tumblr a requirement for soft launch, or might we want to just remove it? (Do people actually still use tumblr? I don't think anyone uses google+!)

**Comment by hackmastera** [comment]
the testing I did was on the sufia master at the time. Maybe we should check again after we hit 7.3

**Comment by hackmastera** [comment]
We could open up a dev box to the world for some development / testing of this. I like the robots.txt idea.

**Comment by jrochkind** [comment]
I believe these are probably working fine, if the app can be reached by the social media sites. 

Do we want to make a dev box that's open to the world to confirm my belief, or just close this?

**Comment by hackmastera** [comment]
We decided to test this in the week or so before soft launch; relabeling as testing

**Comment by MDiMeo** [comment]
Now that the firewall is down, we were able to test this. Facebook, Twitter, Google+, and Tumblr icons each bring the user to a preview page for sharing.
