### ISSUE TITLE
corrupted work data

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#394]
somehow a work got into a state where it had a thumbnail_id and representative_id but no members. there were no failed background jobs.

- [ ] add validation to ensure a work cannot be saved in this state.
- [ ] add error handling to the front-end such that bad data of this sort does not cause an error.

**Comment by jrochkind** [comment]
The error exhibits as an infinite loop "stack level too deep", which makes it hard to track down exactly where it's happening to fix it. I'll work a bit more. 

If the bug is in curation_concerns... we can work around it locally, but I believe curation_concerns is no longer maintained, and I'm not sure I can afford the time to figure out how to send a PR to hyrax instead, but maybe.

**Comment by jrochkind** [comment]
The bug appears to be at `curation_concerns/work_show_presenter.rb", 50`, in the `representative_presenter`. 

One would think we could fix this with a custom override in our own local GenericWorkShowPresenter, but my override is not taking for some reason.  Having trouble figuring out why.

**Comment by jrochkind** [comment]
Could not quite get to the bottom of it upstream, but reported what I have found at:

https://github.com/projecthydra-labs/hyrax/issues/663

I'm going to fix it locally and hackily, I think I could spend all day or more trying to fix it upstream, which does not seem a wise use of time.

**Comment by jrochkind** [comment]
holy cow, at presentation time the presenter may not have access to member_ids or ordered_member_ids, making this hard to fix even locally. This is some really really convoluted architecture.
