### ISSUE TITLE
Styles broken on search results numbers

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#419]
Numbers appear above title; should be in line with title

**Comment by jrochkind** [comment]
So, this is broken in default sufia, and hyrax too I think. 

It looks like _most_ implementers just remove the numbers. 

@MDiMeo @catlu what do you think about removing the numbering, for now anyway?  Most searches on the internet at large don't number their results. (Google, Amazon, etc).  I think it was there in a library context, because especially for library catalogs, and doing reference, remotely, when you don't have shared screen, it's useful to be able to say "Result #2 is what you want when you do this search" or whatever. I'm not sure if that applies to us, and even if it does "useful" isn't the same thing as "absolutely required." :)

If we do want to fix it, I can try to fix it in CSS (Have tried, pretty challenging becuase of how Sufia/BL implements it), or I can try to override views and do the numbering in an entirely different way. 

Notes to myself: If we try to do it with CSS, jcoyne found some hints as to where it's going wrong:

> @jrochkind it looks like the `.row` is wider than the `li`
> @jrochkind `.document` probably needs to have a gutter

**Comment by jrochkind** [comment]
> @jrochkind so I futzed with this awhile. Here’s the problem we have: http://stackoverflow.com/questions/38401119/bootstrap-grid-inside-list-items. AFACT none of the presented solutions are good.
stackoverflow.com
Bootstrap grid inside list items
I want to put Bootstrap 3 rows and col-*s inside my numbered list. More specifically I have a form which allows adding multiple addresses. Each address consists of form fields (street, city, etc.)....

**Comment by jrochkind** [comment]
https://github.com/projecthydra-labs/hyrax/pull/783

**Comment by MDiMeo** [comment]
We're okay with you removing the numbers all together.

**Comment by jrochkind** [comment]
Well, that's a lot easier!
