### ISSUE TITLE
Homepage category: Scientific Education

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#435]
Aggregate using metadata from:

-  Genre
o   Chemistry sets: 16
o   Molecular models: 9

-  Subject
o  Science--study and teaching: 12

**Comment by catlu** [comment]
Hey @jrochkind, I'm not seeing works from this search https://hydra.chemheritage.org/catalog?f%5Bsubject_sim%5D%5B%5D=Science--Study+and+teaching&page=2&search_field=all_fields showing up in the category currently.

**Comment by jrochkind** [comment]
Another typo, sorry, I had "Science--Study and teaching". 

Will fix. 

@catlu, If you would find it easier to try to proof-read my subjects and genres, instead of figuring it out by comparing works, you can do so here: https://github.com/chemheritage/chf-sufia/blob/master/lib/chf/synthetic_category.rb#L22-L83

**Comment by jrochkind** [comment]
In this case, I copied the lowercase 's' from your specification above, so it wasn't my typo, but we clearly all make typos! Case does matter for these.
