### ISSUE TITLE
Change Genre term 'Diagrams' to 'Charts, diagrams, etc.'

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#562]
New URI: http://id.loc.gov/authorities/subjects/sh99001425.html

Will need to update existing data as well, right? Should I make another ticket for that?

**Comment by hackmastera** [comment]
Yes this will require data migration. No need to make another ticket.

**Comment by hackmastera** [comment]
I believe we can do this 100% risk-free with no downtime as follows:

1. Delete the 'Diagrams' term from the list of options
2. Run the data migration task
3. Add the new 'Charts...' term to the list.

I'll test it on dev. If it works, we should notify staff users before we do it since they'll see the term disappear from the form.

**Comment by hackmastera** [comment]
An extra safeguard would be to check for 'Diagrams' on save and change it to the new term so that anyone who uses it after the task has run, but before the option is removed, would get the correct term.

**Comment by hackmastera** [comment]
Steps:
- [ ] Test process on staging
- [ ] Merge #775, deploy
- [ ] Run data migration task (`chf:data_fix:genre_charts`)
- [ ] Merge #776, deploy
