### ISSUE TITLE
Fix citation export tools (with RIS export)

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#565]
To be determined/discussed further:

None of these have been examined to make sure they work with our customized metadata fields. If we aren't able to do this before soft launch, consider removing them until we're able to test / fix them.

maybe on-screen human readable as well as fix endnote, zotero, export. (what do we do with makers? get some samples of how things ought to be cited created by a human). Citation button on viewer?

**Comment by MDiMeo** [comment]
Create RIS file to be used with all 3 export tools.

**Comment by MDiMeo** [comment]
Notes from user testing with 3 researchers on 2/7/2018:
- Everyone saw and knew to use the Export RIS button. If we add a Citation field, two users said they might expect to see it there. All users requested a citation field in addition to the export feature.
- Everyone happy with amount of data that was exported. One user happy to see that it saved as “book” and not “website”, which is sometimes default for online sources even when they’re not websites.
- When viewing a child work in Zotero, one user recommended we change it “Book Selection” instead of “Book”, and then use “Title” as the title of the child work and “Title of Book” as the title of the parent work. (This made sense in this use case, but we would have to look at our metadata and make sure this would work across all types of parent/child works in our diverse collection.)
- One user who used EndNote was confused when trying to import the RIS file into EndNote. She is used to selecting the EndNote file from a drop menu or window when she exports. Couldn’t get it to work the first time because EndNote defaulted to try importing an EndNote file. Upon some fumbling, she switched “Import Option” and selected RIS and it worked. She said she would love if the “?” button had more helpful info instead of just links to the homepage of EndNote, etc.
- “?” button next to Export RIS button didn’t work on IE, but did in Chrome. In IE, it didn’t appear to be an active button and nothing popped up.

**Comment by jrochkind** [comment]
We may be able to provide one-click export to endnote, with a separate link/button, using the RIS format.  Not sure, but here is ostensibly some documentation: http://endnote.com/sites/rm/files/m/direct_export_ris.pdf

We'd have to figure out the right UI.

**Comment by jrochkind** [comment]
@MDiMeo was the use who had trouble with export/import to endnote using Endnote Desktop or Web?  What OS were they using, and what browser? Apparently Firefox might give you the option to open in EndNote, but Chrome will not. http://kbportal.thomson.com/display/2/searchDirect/index.aspx?searchstring=TS_ENIMPORTFAQ2&searchtype=8&searchby=referenceword&Catid=&SubCatid=&att=&remotesite=&search=

**Comment by MDiMeo** [comment]
EndNote Desktop on Windows, and she tried with Chrome and IE. The one thing that was tricky is that she had to use it through Citrix which added some additional layers of complication.

**Comment by MDiMeo** [comment]
Today I user tested with someone who uses the Zotero web extension. His workflow is not to click the export button on any given page, but instead to use the Zotero shortcut button in the top right of his Chrome browser. When he did so, he was confused by the lack of information (no date, no author) and incorrect information (saying it was a website instead of a photograph or manuscript). Then when he used the "export RIS" button and imported the file into the Zotero desktop, he was surprised to find extra information, all correct, and appearing where he wanted it. He was wondering if this happens to him all the time using the Zotero web extension and if he's just never noticed that he's losing so much information or not. He said it works really well with Amazon, which is where he pulls most of his book citations.

Here is the screenshot: 
![digibetanick](https://user-images.githubusercontent.com/11823009/36169206-98b8a338-10c9-11e8-9c83-6416ca5eee97.png)

**Comment by jrochkind** [comment]
A thread in where I ask some questions about Zotero imports: https://forums.zotero.org/discussion/comment/301945/
