### ISSUE TITLE
font size on edit form dropdown is larger

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#605]
subjects autocomplete drop-down displaying in bold & font is definitely larger than is used to be (and than other stuff on the edit form)

**Comment by hackmastera** [comment]
@archivistsarah It's not actually bold but it is larger than it used to be, and than the other stuff on the form.

I bumped up the base size on the whole page; recommended default font sizes have gone up due to increased pixel densities in newer screens.

The UI library that is used on the edit page appears to make these ui menu items sized at 1.1em. So it's always been a bit bigger than the rest of the stuff on the page, but with the increase in base size you've noticed it get larger.

I'm inclined to close this as wontfix but please do go ahead and make a case for this if it's affecting your work.

**Comment by archivistsarah** [comment]
Not affecting my work at all! Closing this.
