### ISSUE TITLE
VIAF autocomplete for Maker field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#63]
https://www.oclc.org/developer/develop/web-services/viaf.en.html

**Comment by hackmastera** [comment]
Spent some time looking at the VIAF API and data this morning, and it's been disappointing. Explored with Cat and here's what we found.
* The json endpoint is not flexible enough; it always searches all indices and cannot be limited to, e.g., personal names. It only ever returns 10 results.
* This means we need to use the SRU / CQL endpoint, which unfortunately only returns XML but that's not a deal-breaker.
* The biggest problem is sort order. There are 2 options: reverse load order (which is meaningless to the point of being unusable) and holdings count. There is no relevance-based sort order. Since the entire authority record is searched, related names, related titles, co-authors, and who knows what else can produce hits. If the hits are on more widely-held records (i.e. more famous people or works) they come out on the top of the list. Example, in the top 10 results of a search for "Butterfield" only 4 of the people are actually named Butterfield.

We need to weigh the results quality of FAST against the inclusiveness of VIAF and decide which we value more. Or maybe consider offering both.

**Comment by hackmastera** [comment]
link to the interface with all the api options: http://viaf.org/viaf/search/viaf

**Comment by hackmastera** [comment]
Okay this has turned out to be pretty entertaining.

![screen shot 2015-08-28 at 1 57 41 pm](https://cloud.githubusercontent.com/assets/845363/9553527/9a1d9c26-4d8d-11e5-81d3-088b176b8177.png)

**Comment by catlu** [comment]
Okay I spent some time going back and forth between the VIAF and FAST autocomplete, and the usability with VIAF is pretty bad (worse than we thought). Out of about 8 or 9 different searches, FAST gave me 100% hits, and VIAF about... 20% at best, and that's after sticking with it and changing the word orders of the searches.

My opinion here is that instead of adding the VIAF corporate subheadings, we just implement FAST and I will work with Museums in putting together a local list of international authorities.

**Comment by hackmastera** [comment]
Thank you for looking into this more deeply. Are you referring to all Maker fields? I.e. get rid of VIAF autocomplete altogether?

If this is definitely the next step we should close this ticket and open a new one for adding FAST to the fields in question.

**Comment by catlu** [comment]
Yeah, I think the VIAF site is still great for cataloger's to use, but the entire autocomplete is kind of a disaster. I'll make a new ticket.
