### ISSUE TITLE
riiif box routing too permissive

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#684]
staging riiif box is currently allowing access to the app ui. but why?

**Comment by jrochkind** [comment]
Was expecting lowercase keys in local_env.yml, but it had uppercase keys, so didn't find the key identifying it as a riiif box. 

staging app has lowercase keys. 

Can manually fix locally, but @sanfordd can you confirm ansible is good?

I think this might be the fourth time a bug was due to typo in local_env.yml, we might want to consider prioritizing having ansible update these with changes and never editing them manually.
