### ISSUE TITLE
improve show page load time performance on large works

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#700]
#698 was a start but we need to do more

**Comment by hackmastera** [comment]
I'd like to also consider what we can push upstream, even if it's only tickets that reference our fixes.

**Comment by jrochkind** [comment]
For sample data: Ramelli in production has 694 members, 196 of which are child works, the others are filesets.

**Comment by jrochkind** [comment]
I made a test record with 50 child works and 0 file sets. 

On riiif branch, it makes 164 requests to solr to render the show page. 

On master branch, only 11. 

So that's probably some of it, the patch to prevent n+1 solr queries doesn't work for child works somehow -- but only in our riiif branch. Maybe riiif branch is asking for something that triggers a solr fetch, that master branch is not. Investigating further.

**Comment by jrochkind** [comment]
having trouble getting width and height into the index. Not sure if it's an artifact of dev:data, or if I'm looking in the wrong place. 

Hmm, none of my filesets have "width" or "height" set on them in fedora. Weird. Are they supposed to?

**Comment by jrochkind** [comment]
yep, just an artifact of my setup. ignore, fixing it.

**Comment by jrochkind** [comment]
I think we did as much of this as we are going to do for now, and can close? Yes @hackmastera ?

#723, #724, #720, #704, #705
