### ISSUE TITLE
introductory text not informative enough

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#759]
Users confused about What CHF is. Users confused about where these objects come from. Users don't know what to expect when they submit a search.

**Comment by MDiMeo** [comment]
How about this?:
Search a growing selection of the Chemical Heritage Foundation's digitized materials in the history of science: artifacts, photographs, advertisements, manuscripts, letters, books, and more.

Want to see the rest of our collections? Check out our [Othmer Library](https://www.chemheritage.org/collections) and the[ Museum at CHF](https://www.chemheritage.org/museum-at-chf). 

NB: I will have to get this approved by communications and have it go through copy editing. Just wanted to post some possible revised text and see if others think this would work with the design and meet our users' needs.

**Comment by MDiMeo** [comment]
Talked with Zack and Clare. They are making changes to the Collections page on the CHF website so that we can just link there. For intro text on our homepage, they recommended doing something more like the NYPL: "Explore 722,575 items digitized from The New York Public Library's collections. This site is a living database with new materials added every day, featuring prints, photographs, maps, manuscripts, streaming video, and more." But I don't think we have time to prioritize coding something that auto displays the number of items in our collection.

Updated text based on conversations with others:
Search a curated selection of the Chemical Heritage Foundation's digitized materials: artifacts, photographs, advertisements, letters, rare books and more. 

The Digital Collections continue to grow everyday. You can also check out the rest of CHF's [collections](https://www.chemheritage.org/collections). 

Does anyone have a strong opinion on this? The other option we discussed was swapping the first sentence for something like "Search over 4,000 digitized items from the Chemical Heritage Foundation: artifacts, photographs, advertisements, letters, rare books and more." [I just think we'd have to remember to update that number every couple of months, or spend the time to auto-generate it.]

**Comment by jrochkind** [comment]
> But I don't think we have time to prioritize coding something that auto displays the number of items in our collection.

This shouldn't actually be that hard, but I agree we don't want to drop everything else to do it right now. Right text that can easily be changed to have this and commit immediately, and file a GH issue asking for it to be changed to include the live number of items, and then we can prioritize changing to include that like we do anything else?

**Comment by MDiMeo** [comment]
Ok! Change text on homepage to this (which has now been approved by Communications):

Search over 4,000 digitized items from the Chemical Heritage Foundation: artifacts, photographs, advertisements, letters, rare books, and more. 

The Digital Collections continue to grow every day. Learn more about the rest of [CHF's collections](https://www.chemheritage.org/collections), which have not all been digitized.

**Comment by jrochkind** [comment]
longer text breaks our CSS. :(

**Comment by jrochkind** [comment]
![screen shot 2017-08-31 at 3 38 14 pm](https://user-images.githubusercontent.com/149304/29942094-a8e15fc8-8e62-11e7-9d76-bb58d0a7c638.png)

**Comment by hackmastera** [comment]
checked with #837 and this is still an issue even without that button. But it shouldn't be too hard to adjust the margins to accommodate the longer text.

I think it's worth considering placing the 2nd paragraph below the search bar, to keep its prominence and because the flow seems more logical / relevant that way.

**Comment by jrochkind** [comment]
I can't figure out any way to fit more text on that page without a more extensive redesign of that page. 

Or, I guess we could just make the font smaller, but that doesn't seem great. 

Is it possible to come up with improved text that's no longer (more words/chars) than what's there now? Or we make the font smaller?  Or we postpone this?  Or we prioritize a redesign of the front page?  Or another option I'm not thinking of?

**Comment by MDiMeo** [comment]
OK, I didn't count characters, but this is shorter:

Search over 4,000 digitized items from the Chemical Heritage Foundation: artifacts, photographs, advertisements, letters, rare books, and more. You can also learn more about the rest of our [collections](https://www.chemheritage.org/collections).

Do you want to try that and see how it looks? I think it was probably a combination of extra words and that extra line break. We could also shorten or edit the list of featured item types.

**Comment by jrochkind** [comment]
Is still gonna require some minor CSS changes to handle the two extra words, the CSS was kind of carefully customized for exactly how much text there was before, but I can do that, it'll work.
