### ISSUE TITLE
Move date to top of facets and expand it by default

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#766]

**Comment by MDiMeo** [comment]
At today's check-in we decided not to move the date facet to the top of the facets, but instead to experiment with adding date search options under the search bar. This is because many users were confused by the histogram and the need to click "apply" in the facet, so we decided we would rather not call attention to a feature that's not working well. The possibility of expanding one category by default may be possible, but we're also not sure how much work this would take. 

Closing this since date issues are addressed in #770 and #876. @catlu - FYI

**Comment by jrochkind** [comment]
I would like to start by moving the Date facet to the top, but not actually having it open by default.  A) It's actually hard to figure out how to get sufia to do this, B) I'm not totally sure it's neccesary/desirable. 

Is this okay as a first step for now, to close this ticket for now, @MDiMeo ?

**Comment by MDiMeo** [comment]
The request to make date more obvious came up AGAIN in yesterday's user testing with a researcher. I now have enough to write a report. It is the most frequently requested item. 

If it's tricky to get it to stay open by default, then, yes, move it to the top and close it for now. But then I think we should seriously consider the drop feature you recommended. I discussed this possibility with the researcher yesterday when date came up during an exit interview and they said that this would meet their needs.

**Comment by jrochkind** [comment]
Cool. I think the new header, which seems to necessarily takes up a lot more space (much higher icon), may require us to rethink/redesign the top of the page one way or another.
