### ISSUE TITLE
Determine strategy to address "users don't know how to open viewer"

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#794]
Move download button? Add help text?

Collect examples

**Comment by jrochkind** [comment]
I would prefer not having the download button _on top_ of the image, because I think the visual design looks a lot better with the top of the image horizontal and lined up with the title. 

But we could put it below the image. Either with or without space between them, either as a square button or just a popup link. Perhaps I was too clever doing it as an overlay trying to save space. 

(Of course, if it needs to go above to make users know what they're doing, we can do that, I'd just like to try to find another solution). 

We could also put a hover effect on the image so it changes color letting you know it's clickable when you hover, or even makes a "click to view" or something like that legend appear.  Doesn't help touch screens, but for mouse users. 

It would be good to see some examples of sites you think have done it well. 

I think it would make sense to do this at the same time as the visual overhaul of that page, so we can make it all work together well designing the page as a whole.

**Comment by catlu** [comment]
After looking at a bunch of viewers, it did seem like a hover/mouseover effect was a popular choice, but used to convey opening or entering the image viewer instead of downloading an image. I didn't feel like I saw any that was a perfect solution, but below are some that have pros:

1) IMO, World Digital Library had the clearest mouseover: https://www.wdl.org/en/item/3980/.
![8](https://user-images.githubusercontent.com/11876037/29840069-abb147a8-8cce-11e7-818f-dd7edfa5ab3e.PNG)
On a different note, the WDL also has a related items list that I can see being useful for us down the line.

2) No screenshot for these examples as it doesn't capture my mouse pointer, but UNR has a mouseover that turns into a magnifying glass with plus sign when over the image: https://library.unr.edu/DigiColl/Item/basqpost/25. Columbia University Libraries does the same thing here: https://dlc.library.columbia.edu/catalog/ldpd:490494. Both sites have additional feature buttons (below for UNR and to the top for Columbia, but the Columbia one is not very visible at all).

3) NLM turns the mouse pointer into an index finger, but also has "view book" and "download" button options. The default function when you click on the image is the "view book": https://collections.nlm.nih.gov/catalog/nlm:nlmuid-9412014-bk.
![3](https://user-images.githubusercontent.com/11876037/29837529-6002fc0a-8cc6-11e7-9fce-5118fbc47130.PNG)
Duke and Free Library also use the index finger pointer on mouseover, but their additional buttons and options are less user friendly: http://library.duke.edu/digitalcollections/oaaaslidelibrary_SLA0343/, https://libwww.freelibrary.org/digital/item/36477.

4) Library of Congress puts an expand icon around the viewer area, with download options below it: https://www.loc.gov/item/2003667933/.
![5](https://user-images.githubusercontent.com/11876037/29837863-6f8b4e4c-8cc7-11e7-9b13-fa2ec3e8ae07.png)

5) Stanford does something similar to LC with a viewer area, but it's neater and uses icons: https://exhibits.stanford.edu/ua-maps-drawings/catalog/wh842xb4798.
![7](https://user-images.githubusercontent.com/11876037/29839279-a498fa18-8ccb-11e7-8aa5-1b8d2b2b4bf1.PNG)

5) UChicago Library uses a corner wrap border for their image viewer functions: https://www.lib.uchicago.edu/e/collections/maps/middleeast19/G7210-1871-K3.html.
![9](https://user-images.githubusercontent.com/11876037/29840863-6c158836-8cd1-11e7-93de-2826198e4008.png)

**Comment by jrochkind** [comment]
First attempt taken in #718, close for now.
