### ISSUE TITLE
No thumbnail generated for image

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#83]
An image was uploaded via Chrome on 9/16/2015 and appeared to be successful (no error messages). The file and metadata are there, but the thumbnail was never generated: 2012.002_b55f21_001.tif Other files were deposited before and after with no problems. 

Do you want to look and see if you can tell what caused this? If you're not sure and it's just something we have to keep an eye out for, I can make a note to integrate this into QA.

**Comment by hackmastera** [comment]
Thanks for opening this. It looks like it's a bug I've been meaning to deal with for a little while but creating a ticket had slipped through the cracks. Actually someone wrote hydra-tech with a solution to the list a couple weeks ago and you can see I responded to thank them at that time! https://groups.google.com/forum/#!searchin/hydra-tech/derivatives$20deadlock/hydra-tech/_L2ysL1A0M8/2agSkvWVFAAJ

**Comment by hackmastera** [comment]
Unfortunately this bug needs to be fixed upstream in hydra-derivatives. I'll open a ticket there and look into submitting a PR.

**Comment by hackmastera** [comment]
On further investigation, our problem is not coming from hydra-derivatives. We may need to look at hydra-derivatives again if / when we start adding digital objects that would use the ffmpeg, document, or jpeg2k derivatives processor. 

So far we're only using the 'images' processor, which can be taken care of just by adding a bit of configuration for mini_magick. Since we're not the only ones who've had this problem, I submitted a generator for this to sufia. I'm also making this fix locally. We can clean up our local Gemfile if my PR is accepted, but that's not urgent.
