### ISSUE TITLE
curator needs to be able to see number of works in a collection and number of public visibility works

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#848]
currently the admin and public view of the collection show page display the total number of works ingested (private and public).

current workflow for getting the number of public works it to set the collection works list to show 100 items, count the pages, then count the number of works on the last page.  

n.b. I don't know that this will be something future curators need to do? might be particular to the volume of Beckman materials, this project, & my stats tracking.

**Comment by jrochkind** [comment]
One additional, but still hacky workaround, workflow is possible now. 

When not logged in (such as in an Incognito window), go to the collection page. Look at the total number of search results displayed above the items.  It will be the number of things in the collection you can see, which since you aren't logged in, will be the public items, and may not match the total items displayed above. 

This whole situation is confusing and could use some cleaning up, but this is perhaps slightly easier workflow for counting public items.
