### ISSUE TITLE
wrong bib num on records?

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#862]
https://digital.chemheritage.org/concern/generic_works/kk91fk52b

Is this one an _incorrectly_ entered bib num? Or something else weird going on?  Bib num entered as  `B10722609`, bib num shows in URL as just `b1072260`, no `9` on the end.  URL to catalog only works with `b1072260`,  without `9` on the end.  

There are a bunch of other records in that same collection with that same (wrong?) bib num, and same (without the -9) link to catalog in 'related links' too. 

Related to work I'm doing to auto-gen catalog links for #718

**Comment by catlu** [comment]
@jrochkind Anna and I discovered earlier on that the correct bib number should be b[7-digits]. When a user gets the number from Sierra, it comes with an extra digit, which is the check digit, but the actual bib number that goes with the URL is the 7-digit one. If there's an easy way to lop the last digit off during auto-gen, let me know. Otherwise, I can try to batch fix those Beckman records with @archivistsarah.

**Comment by jrochkind** [comment]
Aha. Is the "real" bib number always 7 digits?  

Are metadata entererers entering them properly as a 7 digit one now?

We'd probably want to bulk fix them at some point, if we ever want to use this for other kinds of linking. 

But for the meantime, I can have my code just ignore an 8th digit when generating catalog links, not a problem. If it's true that they are always 7 digits. 

But are they ever less than 7 digits? Could they become more than 7 digits if we get more records? It's def kind of a mess.

**Comment by catlu** [comment]
I've been entering them as 7 digits (since I'm usually first pass and the bib number is a required field) since we discovered that, but we also figured if people occasionally had an 8-digit one, it'd be easy to just ignore the 8th digit like now. It can be really confusing to curators as both numbers show up in the Sierra record! Mess for sure. They aren't ever less than 7 as far as I know. More? We'd have to ask lib folks.

**Comment by jrochkind** [comment]
OK. I can probably mostly get it working for now, but if we ever want to do more integration, we'll have to figure it out. Like a link _from_ a catalog record to "any digital collection objects associated with this record" sounds like a pretty good idea, but isn't going to work with wrong bib nums. 

But for now, I can probably handle it, so long as no _real_ bib numbers are ever 8 digits.
