### ISSUE TITLE
Staging - batch upload thumbnails not showing up on search results page

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#895]
Did two batch work upload tests on different days. Out of the 9 total files, 8 of them didn't show thumbnails on the search results page. (They should also be front page right now when doing a blank search.) Image viewer and derivative downloads work fine though. Samvera IDs are 47429971p, b8515n91s, b8515n91s, 1v53jx639, c821gk46t, kd17ct53c, c247ds69n, tm70mv78z. The one with a thumbnail is 7h149q391.

**Comment by jrochkind** [comment]
Sorry, I should know this by now, but can you tell me what screen(s) you use to do batch uploads? I go where and do what to do a batch upload like you do?

**Comment by catlu** [comment]
Here's the easiest way: Go to menu bar > Works > Batch Create.

The other method is just to go create a new work and then at the very top of the Description tab (above title), you'll see a line that says "To create a separate work for each of the files, go to Batch upload."

**Comment by jrochkind** [comment]
OK, this is fixed in staging. 

There is some new behavior that's a bit weird. While you are waiting for thumbs to be created:

At FIRST you'll get a placeholder image. 

LATER, while thumbs aren't done but at a different stage of not done, you'll get a 'broken image', which will show up as a textual alt tag taking the place of the image. Which in this case is the annoying words: "thumb standard".  This means it's just not done yet. 

FINALLY, when it's really done you get the actual thumbnail. 

That weird second step is sort of an accidental implementation detail. I should maybe fix it though, for other reasons. But how annoying do you think it is, @catlu ?

**Comment by catlu** [comment]
Not annoying at all for me @jrochkind. Your call!

**Comment by jrochkind** [comment]
It would also happen if one or more of our new S3 thumbs mistakenly went missing. I'd rather show the user a well-formatted broken image in that case, and I think I can easily do it with JS, let's see! Sorry for the running dialog!

**Comment by jrochkind** [comment]
also a better alt label, or no alt label, is probably preferable for accessibility to "Standard thumb" as an alt label. :)
