### ISSUE TITLE
Neville Collection thumbnail

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#899]
Image from here: https://digital.chemheritage.org/concern/generic_works/m039k491c/viewer/bn999752k

Crop of--
	
clu 3:27 PM
cool, do you have any preference for a section to crop? i can put it in the ticket
mdimeo 3:27 PM
that guy on his knees!
3:27
and his crazy tent
clu 3:27 PM
awesome
mdimeo 3:27 PM
i guess you couldn't crop the whole tent though (edited)
clu 3:28 PM
maybe enough to capture his book

**Comment by jrochkind** [comment]
@MDiMeo am I still waiting for the crop before I can do this?  Or is the crop available somewhere? If so, add where I get the crop from to this ticket, and same for #891? Thanks!

(Or are you asking _me_ to crop?  I'd prefer someone else with better image skills and better sense of what they want do the crop!)

**Comment by MDiMeo** [comment]
We previously tried giving Anna crops and she almost always ended up re-cropping them anyway because they didn't meet her needs. I'm honestly not sure what the problem was, but I know there were miscommunications when she gave specs to Jay. If you can articulate for us exactly what you need, one of us with access to Photoshop can do it and send it to you. Anna found it quicker to do it herself in the command line, and those are the steps that are outlined in the github doc I shared yesterday. However, the rest of us don't have access to the command line on our work computers and would need to have the specs from that doc translated into something we can use in Photoshop. Let me know if you think you can do it or if you want to revisit the workflow!

**Comment by MDiMeo** [comment]
The crop is here: https://github.com/chemheritage/chf-sufia/blob/377a0e62e60e3a60a527de498883d1235bc9a6d7/docs/image_crops.md

I think what you propose sounds reasonable! I can try doing that tomorrow, or @catlu can jump in today if she wants. I think we both know what we're after here.

**Comment by catlu** [comment]
I'm on it @MDiMeo @jrochkind.

**Comment by jrochkind** [comment]
@catlu I think you said you'd put crops on the P drive? 

If you put them in `Othmer Library/Digital Collections/Crops for Hydra Redesign/cropped tiffs/collections`, can you tell me the filename with the one for this ticket? Plus same on other ticket #891?

**Comment by catlu** [comment]
1c18dg55j_full.tiff
