### ISSUE TITLE
Non-admin logged in users can't access viewer & thumbnails

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#914]
[Example work this happened to: 2b88qc81s]

When logged in as a non-admin user (aaugustyniak@chf) with shared edit access to a work, these were the issues:

1) Clicking on the representative image does not bring up image viewer.
2) Clicking on "view" button does not bring up image viewer.
3) Additional filesets that are part of the work do not show up as thumbnails.

**Comment by jrochkind** [comment]
Thanks. Can you tell me how in the UI I give someone shared edit access, to help me try to reproduce?

**Comment by catlu** [comment]
Yep @jrochkind, in the edit form, navigate to Share tab > Share work with other users > select the edit option > + button.

**Comment by MDiMeo** [comment]
I've heard back from Joel Klein (another person with a non-admin user account) and received more clarification on the bug he tried describing to me yesterday. He confirmed that the issue is related to him not being logged in and is not specific to the browser he is using. He said: "I click on “view” and it changes from light gray to dark gray but nothing else happens. The image viewer doesn’t open at all. Also, the magnifying glass doesn’t do anything when I click directly on the image." He did not give a specific page or object, but at least now I'm sure it's the same bug @catlu is describing above and not a new one.

**Comment by jrochkind** [comment]
OK, I don't really understand Joel's problem, but hopefully it's part of the same one, we'll get this reproducible one fixed and then check back with him.

**Comment by jrochkind** [comment]
Succesfully reproduced in development, so that's good.

**Comment by jrochkind** [comment]
Ah, ye old "AND" where should have been an "OR".
