### ISSUE TITLE
Ingested files not processing

### ISSUE THREAD

**Issue by mhpmiller** [chemheritage/chf-sufia#982]
Images for works ingested today (Tuesday late morning/early afternoon) are not displaying. (Material ingested on Friday looks just fine.) Works: 6w924c74z, 0p096786p, 1g05fc36k.

1g05fc36k (single-file) uses 6000.tif (available on digitization drive, Beckman\ready for ingest). Tried uploading a new version, but no luck. File Details still show "Fixity checks have not yet been run on this object" and the Characterization shows on file format and mime type.

**Comment by jrochkind** [comment]
So it does not appear to be an issue with thumbnail generation, rather the file is not ingested at all. 

Just in case, I rolled back to the last deploy _before_ the ones I did today, although the ones I did today were quite minor tweaks to labels and such. 

After doing this, I could still reproduce the failure to ingest a file on production. 

The error I get is especially weird, and does not seem to be the same error others have gotten. Here's my error: https://app.honeybadger.io/projects/53196/faults/36694450

That's an error from fedora itself: "Ldp::HttpError: STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: java.io.IOException: No such file or directory at org.modeshape.jcr.value.binary.FileSystemBinaryStore.storeValue(FileSystemBinaryStore.java:128)"

Strangely, while this is probably an error in a bg job, the bg jobs admin does _not_ report any errors more recent than November. Not sure why. https://digital.sciencehistory.org/admin/queues/failed

Honeybadger says that's the first time that error occured, so that's not what has happened to others.  Others errors may be:

* https://app.honeybadger.io/projects/53196/faults/36690438
* https://app.honeybadger.io/projects/53196/faults/36688869

All those are from app-prod, not app-jobs. (The initial ingest bg jobs do run on app-prod). 

I deployed "master" to staging, and _was_ succesfully able to ingest, no problem. 

So I don't think this is an app code problem. I think it's an environment problem of some kind. Brainstorming:

* Disk full somewhere? fedora machine or app-prod?
* Fedora has gone crazy and needs to be restarted?
* Network problems between app and fedora machine?

I'm not sure how to check any of these things (or restart fedora) without @sanfordd

**Comment by jrochkind** [comment]
I do not know how to ssh to the fedora machine (IP address or hostname), and do not know if I have an account that can get there anyway.

**Comment by jrochkind** [comment]
Esmé on slack suggests, from that 500 modeshape error:

> is there enough temp space to hold the files you're uploading? i think that could be a problem trying to save the file to temp space and then copy it over after it finishes uploading

**Comment by sanfordd** [comment]
I don't see a shortage on fedora actively for storage space, we could use more /tmp space but it's not full at the moment.

**Comment by sanfordd** [comment]
Ok, I'm seeing a fedora client access error. I tried directly hitting the location and was able to get Fedora to pass me the tiff file for the object when accessing it as the fedora administrative user. 

> INFO 07:36:20.297 (FedoraLdp) GET resource 'prod/q2/37/hs/45/q237hs45t/files/64f5ba0c-48bc-4544-96bc-97195f4a92b6'
> Feb 11, 2018 7:36:20 AM org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
> SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
> org.glassfish.jersey.server.internal.process.MappableException: ClientAbortException: java.net.SocketException: Connection reset

Digging into that one, it might be a limits.conf restriction we're hitting according to a few searches but that seems odd to be coming out under this usage.

**Comment by sanfordd** [comment]
Alright, that seems unrelated to our error, we're seeing something like this
`INFO 11:38:38.993 (FedoraLdp) PUT resource 'prod/57/12/m7/29/5712m729j/files/21cd1484-1bb5-4c32-83f9-1990f62ecc91'`
`ERROR 11:38:39.539 (RepositoryExceptionMapper) Caught a repository exception: java.io.IOException: No such file or directory`

The files, when I pushed a test one up myself, do appear inside the actual fcrepo binary directory. They're on the disk in the location where their sha1 checksum indicates they should be, but they seem to not be associated with the object in fcrepo somehow.

**Comment by sanfordd** [comment]
I restarted fedora and this somehow fixed the problem. Unsure why, I'll contact the fcrepo listserve to see if anyone has ideas on that.
